// Generated from shared/webhook-types.ts.
// scripts/check-webhook-event-parity.mjs fails CI if the two drift.
export const WEBHOOK_EVENT_TYPES = [
  "message.sent",
  "message.delivered",
  "message.read",
  "message.failed",
  "message.bounced",
  "message.retrying",
  "message.received",
  "message.opt_out",
  "message.opt_in",
  "verification.created",
  "verification.delivered",
  "verification.verified",
  "verification.expired",
  "verification.failed",
  "verification.resent",
  "verification.delivery_failed",
  "conversation.created",
  "conversation.updated",
  "draft.created",
  "draft.approved",
  "draft.rejected",
  "contact.auto_flagged",
  "contact.marked_valid",
  "contacts.lookup_completed",
  "contacts.bulk_marked_valid",
  "brand.verified",
  "brand.failed",
  "campaign.approved",
  "campaign.rejected",
  "campaign.suspended",
  "assignment.confirmed",
  "assignment.failed",
  "rcs_brand.verified",
  "rcs_brand.failed",
  "rcs_agent.testing",
  "rcs_agent.live",
  "rcs_agent.rejected",
  "rcs_agent.action_required",
  "port.completed",
  "port_out.requested",
  "port_out.completed",
  "port_out.rejected",
  "port_out.cancelled",
  "number.activated",
  "number.failed",
  "number.requirements_required",
  "number.released",
  "whatsapp_account.connected",
  "whatsapp_account.failed",
  "whatsapp_template.approved",
  "whatsapp_template.rejected",
  "whatsapp_template.paused",
  "call.started",
  "call.completed",
  "call.recording.ready",
  "short_code.action_required",
  "short_code.rejected",
  "short_code.filed",
  "short_code.live",
] as const;

export type WebhookEventType = (typeof WEBHOOK_EVENT_TYPES)[number];
